//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeGlitzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeGlitzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —
        ///Stench
        ///Drizzle
        ///Speed Boost
        ///Battle Armor
        ///Sturdy
        ///Damp
        ///Limber
        ///Sand Veil
        ///Static
        ///Volt Absorb
        ///Water Absorb
        ///Oblivious
        ///Cloud Nine
        ///Compound Eyes
        ///Insomnia
        ///Color Change
        ///Immunity
        ///Flash Fire
        ///Shield Dust
        ///Own Tempo
        ///Suction Cups
        ///Intimidate
        ///Shadow Tag
        ///Rough Skin
        ///Wonder Guard
        ///Levitate
        ///Effect Spore
        ///Synchronize
        ///Clear Body
        ///Natural Cure
        ///Lightning Rod
        ///Serene Grace
        ///Swift Swim
        ///Chlorophyll
        ///Illuminate
        ///Trace
        ///Huge Power
        ///Poison Point
        ///Inner Focus
        ///Magma Armor
        ///Water Veil
        ///Magnet Pull
        ///Soundproof
        ///Rain Dish
        ///Sand Stream
        ///Pressure
        ///Thick Fat
        ///Ear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string abilities {
            get {
                return ResourceManager.GetString("abilities", resourceCulture);
            }
        }

        internal static string balls {
            get {
                return ResourceManager.GetString("balls", resourceCulture);
            }
        }

        internal static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }

        internal static string genders {
            get {
                return ResourceManager.GetString("genders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None)
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Parlyz Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///EnergyPowder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max Elixir
        ///Lava Cookie
        ///Blue Flute
        ///Yellow Flute
        ///Red Flute
        ///Black Flute
        ///White Flut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }

        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Littleroot Town
        ///Oldale Town
        ///Dewford Town
        ///Lavaridge Town
        ///Fallarbor Town
        ///Verdanturf Town
        ///Pacifidlog Town
        ///Petalburg City
        ///Slateport City
        ///Mauville City
        ///Rustboro City
        ///Fortree City
        ///Lilycove City
        ///Mossdeep City
        ///Sootopolis City
        ///Ever Grande City
        ///Route 101
        ///Route 102
        ///Route 103
        ///Route 104
        ///Route 105
        ///Route 106
        ///Route 107
        ///Route 108
        ///Route 109
        ///Route 110
        ///Route 111
        ///Route 112
        ///Route 113
        ///Route 114
        ///Route 115
        ///Route 116
        ///Route 117
        ///Route 118
        ///Route 119
        ///Route 120
        ///Route 121
        ///Route 122
        ///Route 123
        ///Route 12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ———
        ///Pound
        ///Karate Chop
        ///Double Slap
        ///Comet Punch
        ///Mega Punch
        ///Pay Day
        ///Fire Punch
        ///Ice Punch
        ///Thunder Punch
        ///Scratch
        ///Vise Grip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///Sonic Boom
        ///Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moves {
            get {
                return ResourceManager.GetString("moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string natures {
            get {
                return ResourceManager.GetString("natures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_e {
            get {
                object obj = ResourceManager.GetObject("personal_e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_fr {
            get {
                object obj = ResourceManager.GetObject("personal_fr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_lg {
            get {
                object obj = ResourceManager.GetObject("personal_lg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_rs {
            get {
                object obj = ResourceManager.GetObject("personal_rs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///Pol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string species {
            get {
                return ResourceManager.GetString("species", resourceCulture);
            }
        }
    }
}
